# Generated by Django 6.0 on 2025-12-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='reels_thumbs/'),
        ),
    ]
