# Generated by Django 6.0 on 2025-12-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0002_reel_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="color",
        ),
    ]
