# Generated by Django 6.0 on 2025-12-19 22:09

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0002_reel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(default="#cccccc", max_length=7),
        ),
        migrations.AlterField(
            model_name="reel",
            name="thumbnail",
            field=models.ImageField(
                null=True, storage=storages.backends.s3.S3Storage(), upload_to="reels"
            ),
        ),
    ]
