# Generated by Django 6.0 on 2025-12-20 18:35

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0003_alter_category_color_alter_reel_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="color",
        ),
        migrations.AlterField(
            model_name="reel",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="reels",
            ),
        ),
    ]
