# Generated by Django 6.0 on 2025-12-28 17:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("exchange", models.CharField(blank=True, default="", max_length=40)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("stock", "Action"), ("etf", "ETF"), ("reit", "REIT")],
                        default="stock",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="div_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ticker"],
                "unique_together": {("user", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="DividendEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_date", models.DateField()),
                ("pay_date", models.DateField()),
                (
                    "amount_per_share",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimé"),
                            ("declared", "Déclaré"),
                            ("received", "Reçu"),
                        ],
                        default="estimated",
                        max_length=10,
                    ),
                ),
                ("is_net_amount", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_events",
                        to="dividends.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["pay_date", "ex_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="DividendPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "withholding_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dividend_payments",
                        to="dividends.asset",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="dividends.dividendevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=14)),
                ("price", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="dividends.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="dividendevent",
            index=models.Index(
                fields=["pay_date"], name="dividends_d_pay_dat_561bae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendevent",
            index=models.Index(
                fields=["ex_date"], name="dividends_d_ex_date_1aed7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendevent",
            index=models.Index(fields=["status"], name="dividends_d_status_6f20e2_idx"),
        ),
        migrations.AddIndex(
            model_name="dividendpayment",
            index=models.Index(fields=["date"], name="dividends_d_date_b99d79_idx"),
        ),
    ]
