# Generated by Django 6.0 on 2025-12-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="last_price_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
