# Generated by Django 6.0 on 2025-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0002_transaction_last_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="price_symbol",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
