# Generated by Django 6.0 on 2025-12-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0003_transaction_price_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="last_price",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="last_price_updated_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="price_symbol",
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="price_symbol",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
