# Generated by Django 6.0 on 2025-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0004_remove_transaction_last_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="last_price",
        ),
        migrations.AddField(
            model_name="asset",
            name="ast_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="dividendevent",
            name="source",
            field=models.CharField(default="yfinance", max_length=20),
        ),
    ]
