# Generated by Django 6.0 on 2025-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0005_remove_asset_last_price_asset_ast_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividendevent",
            name="pay_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="dividendevent",
            unique_together={("asset", "ex_date", "amount_per_share")},
        ),
    ]
