# Generated by Django 6.0 on 2025-12-29 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0006_alter_dividendevent_pay_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="last_price_updated_at",
            new_name="last_price_asof",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="ast_price",
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_price_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="dividendevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("estimated", "Estimé"),
                    ("declared", "Déclaré"),
                    ("received", "Reçu"),
                ],
                default="declared",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "ticker"], name="dividends_a_user_id_820077_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "is_active"], name="dividends_a_user_id_d118cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendevent",
            index=models.Index(
                fields=["asset", "ex_date"], name="dividends_d_asset_i_a6c491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividendpayment",
            index=models.Index(
                fields=["asset", "date"], name="dividends_d_asset_i_042dad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["asset", "date"], name="dividends_t_asset_i_487376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="dividends_t_date_7727bb_idx"),
        ),
    ]
