# Generated by Django 6.0 on 2025-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dividends",
            "0007_rename_last_price_updated_at_asset_last_price_asof_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
