# Generated by Django 6.0 on 2025-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0008_asset_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="symbol",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
