# Generated by Django 6.0 on 2025-12-31 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0009_asset_symbol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="isin",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "price_symbol"], name="dividends_a_user_id_4734be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["asset", "type", "date"], name="dividends_t_asset_i_bc5bbc_idx"
            ),
        ),
    ]
