# Generated by Django 6.0 on 2025-12-19 22:09

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_is_public_post_owner_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True, storage=storages.backends.s3.S3Storage(), upload_to="posts"
            ),
        ),
    ]
