# Generated by Django 6.0 on 2025-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_admin_only",
            field=models.BooleanField(default=False),
        ),
    ]
