# Generated by Django 6.0 on 2025-12-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_is_admin_only"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_admin_only",
            new_name="is_superuser_only",
        ),
    ]
