# Generated by Django 6.0 on 2025-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_rename_is_admin_only_post_is_superuser_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts"),
        ),
    ]
