# Generated by Django 6.0 on 2025-12-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("purchase_date", models.DateField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "notary_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "agency_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_capital",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("annual_rate", models.DecimalField(decimal_places=3, max_digits=6)),
                ("years", models.PositiveIntegerField()),
                (
                    "insurance_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan",
                        to="immo.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("works", "Travaux"),
                            ("repair", "Réparation"),
                            ("tax", "Taxes"),
                            ("charges", "Charges copro"),
                            ("insurance", "Assurance"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="immo.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("rent_hc", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_periods",
                        to="immo.property",
                    ),
                ),
            ],
        ),
    ]
