# Generated by Django 6.0 on 2025-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="market_value_est",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="selling_fees_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
