# Generated by Django 6.0 on 2025-12-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0002_property_market_value_est_property_selling_fees_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPricePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price_per_sqm", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_points",
                        to="immo.property",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("property", "date")},
            },
        ),
    ]
