# Generated by Django 6.0 on 2025-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0003_marketpricepoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="surface_sqm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
