# Generated by Django 6.0 on 2025-12-21 20:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0004_property_surface_sqm"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="goodwill_eur_per_sqm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ajustement ajouté au prix marché €/m² pour estimer la valeur (travaux, qualité, vue, etc.)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="selling_fees_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
