# Generated by Django 6.0 on 2025-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0005_property_goodwill_eur_per_sqm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="parking",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
