# Generated by Django 6.0 on 2025-12-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immo", "0006_property_parking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="parking",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
